// Auto generated by genmodel. DO NOT EDIT.
package model

import (
	"encoding/json"

	"github.com/noctf/scoreserver/db"
)

func (problem Problem) MarshalJSON() ([]byte, error) {
	buf, err := json.Marshal(problem)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func (problem *Problem) Load(tx *db.Tx, id string) error {
	pdb := db.Problem{}
	if err := pdb.LoadByID(tx, id); err != nil {
		return err
	}
	if err := problem.FromRow(&pdb); err != nil {
		return err
	}
	return nil
}

func (problem *Problem) FromRow(pdb *db.Problem) error {
	problem.ID = pdb.ID
	problem.Title = pdb.Title
	problem.IsFlag = pdb.IsFlag
	problem.Flag = pdb.Flag
	problem.Statement = pdb.Statement
	problem.Score = pdb.Score
	return nil
}

func (problem *Problem) ToRow(pdb *db.Player) error {
	pdb.ID = problem.ID
	pdb.Title = problem.Title
	pdb.IsFlag = problem.IsFlag
	pdb.Flag = problem.Flag
	pdb.Statement = problem.Statement
	pdb.Score = problem.Score
	return nil
}
